#!/bin/bash

# digit input 1 on GPIO1_25
PIN_DIN1=57
# digit input 2 on GPIO1_27
PIN_DIN2=59

status=$(echo "P 3 5 1" | serial_rw.py)
status=$(echo "P 3 6 0" | serial_rw.py)
# echo -> translate '\x0a' to ' '
status=`echo $(gpio input $PIN_DIN1; gpio input $PIN_DIN2)`
echo status1=@${status}@
[ "$status" = "1 0" ] || { exit 1; }

status=$(echo "P 3 5 0" | serial_rw.py)
status=$(echo "P 3 6 1" | serial_rw.py)
# echo -> translate '\x0a' to ' '
status=`echo $(gpio input $PIN_DIN1; gpio input $PIN_DIN2)`
echo status2=@${status}@
[ "$status" = "0 1" ] || { exit 2; }

exit 0

