#!/bin/bash
# pwm output script

function usage() {
	cat <<EOF
Usage
  to set output ehrpwm1a, duration = 3s, freq = 8000Hz
  $0 1 A 3 8000
EOF
	exit 2
}

sys_map=(0 0 0)
hard_nr=$1
sub_nr=$(echo $2 | tr a-z A-Z )
duration=${3:-3}
freq=${4:-1000}

[ "$hard_nr" == "" ] || [ "$hard_nr" -ge ${#sys_map[@]} ] && {
	echo "Invalid pwm # $hard_nr"
	echo
	usage
}

channel_nr=$(expr index "AB" "$sub_nr") 
[ "$channel_nr" -eq 0 ] && {
	echo "Invalid pwm channel # $2"
	echo
	usage
}
channel_nr=$(( channel_nr - 1))

sys_nr=${sys_map[$hard_nr]}
sys_dir=/sys/class/pwm/pwmchip$sys_nr
cd $sys_dir || {
	echo "directory $sys_dir unexist"
	exit 1
}

# intialize port
channel_dir=pwm-$sys_nr\:$channel_nr
[ -d $channel_dir ] && {
	(cd $channel_dir; echo 0 > enable)
	sleep 0.2;
	echo $channel_nr > unexport
	sleep 0.2;
}
echo $channel_nr > export
cd $channel_dir



# period & duty_cycle
period=$(( 1000000000 / freq))
echo $period > period
echo $(( period / 2 )) > duty_cycle


# output for a while
echo 1 > enable
[ "$duration" == "u" ] && { exit 0; }
sleep $duration
echo 0 > enable

# cleanup
cd $sys_dir
echo $channel_nr > unexport

exit 0

