#!/bin/bash
#
# Copyright (c) 2018 Baozhu Zuo <zuobaozhu@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -x
exec 1>/var/log/$(basename $0).log 2>&1
#enable i2c interface
dtparam i2c_arm=on
modprobe i2c-dev

#enable spi interface
dtparam spi=on
sleep 1


is_1a=
is_35=
is_3b=

addr_update() {
    is_1a=$(i2cdetect -y  1 0x1a 0x1a | grep 1a | awk '{print $2}')
    is_35=$(i2cdetect -y  1 0x35 0x35 | grep 35 | awk '{print $2}')
    is_3b=$(i2cdetect -y  1 0x3b 0x3b | grep 3b | awk '{print $2}')
}

wait_insert() {
    while true; do
        sleep 0.5
        addr_update
        if [ "x${is_1a}" == "x1a" ] || [ "x${is_3b}" == "x3b" ] || [ "x${is_35}" == "x35" ] ; then
            break
        fi
    done
}
 
wait_leave() {
    while true; do
        sleep 0.5
        addr_update
        if [ "x${is_1a}" == "x1a" ] || [ "x${is_3b}" == "x3b" ] || [ "x${is_35}" == "x35" ] ; then
            continue
        fi
        break
    done
}
        
if true; then
    echo "install 6mic"
    sleep 1
    # hw=$(aplay -l | grep seeed8micvoicec | awk '{print $2}' | sed 's/://')
    hw=1

    cp /etc/voicecard/asound_6mic.conf /etc/asound.conf

    old=$(cat /etc/asound.conf | grep hw: | awk 'NR==1 {print $2}' | sed 's/\"//g')

    sed -i -e "s/${old}/hw:${hw},0/g" /etc/asound.conf  

    cp /etc/voicecard/ac108_6mic.state /var/lib/alsa/asound.state
fi

alsactl restore

#Fore 3.5mm ('headphone') jack
amixer cset numid=3 1

pushd /root/4mics_hat
rm -f handler-installed
python3 pixels.py &
# wait handler installed
while [ ! -e handler-installed ]; do
    sleep 1
done
pid_led=$!
popd


while true; do
    wait_insert

    # start led flashing
    kill -s SIGUSR1 $pid_led
    sleep 1
    # stop  led flashing
    ( sleep 6; kill -s SIGUSR2 $pid_led )&

    dtoverlay seeed-8mic-voicecard || true

    pushd /root/EMSTS
    ./start
    popd

    killall aplay
    dtoverlay -r seeed-8mic-voicecard || true

    wait_leave
done


